### ISSUE TITLE
demo03

### ISSUE THREAD

**Issue by huanglintian** [ruanyf/mocha-demos#3]
执行递归测试脚本时最后执行结果错误输出，单独测试的话是没有这个错误输出的，麻烦可以告诉一下是什么问题吗？
![image](https://user-images.githubusercontent.com/11827846/34513628-2625e424-f0a4-11e7-90f1-99d09358c33b.png)

**Comment by ruanyf** [comment]
打开`demo03/test/mocha.opts`文件，删除第三行`--growl`。

**Comment by huanglintian** [comment]
Thinks!
